feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt
Camera preview would freeze when the previewUiState values were changed. This fix prevents that by only considering `previewUiState.cameraState` in the LaunchedEffect where the camera is started/stopped.
=> Fix camera preview freezing bug

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt
Also add some logging to view model functions.
The coroutine that's suspended awaiting the deferredSurfaceProvider wasn't being resumed because the deferredSurfaceProvider object was different each time.
This fix addresses that.
=> Fix problem with LaunchedEffect having to depend on cameraState

app/src/main/java/com/google/jetpackcamera/MainActivity.kt, app/src/main/java/com/google/jetpackcamera/MainActivityViewModel.kt, data/settings/src/androidTest/java/com/google/jetpackcamera/settings/LocalCameraAppSettingsRepositoryInstrumentedTest.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/JcaSettingsSerializer.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/LocalSettingsRepository.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/SettingsRepository.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/model/CameraAppSettings.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/model/FlashModeStatus.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/test/FakeSettingsRepository.kt, data/settings/src/main/proto/com/google/jetpackcamera/settings/flash_mode.proto, domain/camera/build.gradle, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraUseCase.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/test/FakeCameraUseCase.kt, feature/preview/build.gradle, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewUiState.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/test/java/com/google/jetpackcamera/feature/preview/PreviewViewModelTest.kt, feature/settings/src/androidTest/java/com/google/jetpackcamera/settings/CameraAppSettingsViewModelTest.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsUiState.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsViewModel.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/ui/SettingsComponents.kt, feature/settings/src/main/res/values/strings.xml
This is a PR that enables the user to change the default flash mode of the rear camera from the Settings Screen. Here is some info on the more notable changes in the files.
**Misc. Changes**
changed the name of the `Settings` class to `CameraAppSettings`
**Changes to Datastore**
created `flash_mode.proto` enum schema representing flash mode status of on, off, and auto
added `flash_mode_status` value to `jca_settings.proto`
add `flash_mode_status` to `CameraAppSettings`
add `updateFlashModeStatus` to `LocalSettingsRepository`
**Changes connecting cameraUseCase to settings values**
_PreviewViewModel.kt_ & _PreviewUiState.kt_
- added settingsRepository as parameter for PreviewViewModel (read-only) 
- add currentCameraSettings value to PreviewUiState. ViewModel will provide the value of the …
=> Connect CameraUseCase to settings data and implement rear camera flash

.idea/androidTestResultsUserPreferences.xml, .idea/misc.xml, data/settings/src/androidTest/java/com/google/jetpackcamera/settings/LocalSettingsRepositoryInstrumentedTest.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/JcaSettingsSerializer.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/LocalSettingsRepository.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/SettingsRepository.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/model/CameraAppSettings.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/test/FakeSettingsRepository.kt, data/settings/src/main/proto/com/google/jetpackcamera/settings/jca_settings.proto, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraUseCase.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/test/FakeCameraUseCase.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/test/java/com/google/jetpackcamera/feature/preview/PreviewViewModelTest.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsViewModel.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/ui/SettingsComponents.kt
This change enables user to set default startup camera orientation front settings screen, and an on-screen button to flip camera. Styling is still WIP but functionality is complete.
Heres pointers for the notable changes here:
**Store available lens information**
_LocalSettingsRepository_
`updateAvailableCameraLens` function stores the availability status of the front and rear camera into datastore. this information can be used as a condition to disable elements within the app from changing the current lens should only one be available.
_CameraXCameraUseCase_ 
* add coroutine dispatcher and settingsRepository parameter to constructor
* launches a coroutine to  set the  available camera lens in settingsRepository
**Functionality to designate front/rear camera**
_CameraXCameraUseCase_
* …
=> Implement flip camera

app/src/main/java/com/google/jetpackcamera/ui/JcaApp.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt
Fix crashing bug that occurs when attempting to navigate back to the preview screen _after_ using a quick setting that rebinds use cases
=> fix bug when navigating to preview from settings screen

app/src/main/AndroidManifest.xml
Also removing redundant `android:label` (already defined at app level)
=> Lock the app to portrait orientation

camera-viewfinder-compose/build.gradle, camera-viewfinder-compose/src/main/java/com/google/jetpackcamera/viewfinder/CameraPreview.kt, camera-viewfinder-compose/src/main/java/com/google/jetpackcamera/viewfinder/surface/CombinedSurface.kt, camera-viewfinder-compose/src/main/java/com/google/jetpackcamera/viewfinder/surface/Texture.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraUseCase.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/test/FakeCameraUseCase.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt
In the `PreviewScreen`, I created a value that keeps track of the View information from the CameraPreview composable. I just pass down a callback function from CameraPreview -> PreviewSurface -> CombinedSurface -> Texture to set that value.
When the screen is tapped, then the display, height, and width information of the view is provided to `PreviewViewModel`'s tapToFocus(), which is then provides that info to `cameraUseCase.tapToFocus` to create a metering point and action to focus.
=> implement tap to focus

feature/quicksettings/src/main/java/com/google/jetpackcamera/feature/quicksettings/QuickSettingsScreen.kt, feature/quicksettings/src/main/java/com/google/jetpackcamera/feature/quicksettings/ui/QuickSettingsComponents.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/ui/SettingsComponents.kt
Just a quick refactor for quality, readability, and future ease of development, no changes to existing functionality
* overload QuickSettingUiItem to avoid repetitive code
* added enabled condition parameter for the SingleChoiceSelector component
=> settings refactor for readability

app/build.gradle, app/src/main/java/com/google/jetpackcamera/ui/JcaApp.kt, build.gradle, camera-viewfinder-compose/build.gradle, core/common/build.gradle, data/settings/build.gradle, domain/camera/build.gradle, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraUseCase.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/EmptySurfaceProcessor.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/SingleSurfaceForcingEffect.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/test/FakeCameraUseCase.kt, feature/preview/build.gradle, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewUiState.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/main/res/values/strings.xml, feature/quicksettings/build.gradle, feature/settings/build.gradle, settings.gradle
- Update AGP version (we need a version that supports sdkTarget 34)
- Update sdkTarget and compileSdk to 34 (we need this in order to use CameraX 1.3.0)
- Use androidx.dev to get CameraX version 1.3.0-SNAPSHOT
- Implement Single stream capture by forcing stream sharing with an empty CameraEffect
- Some minor refactoring to CameraXCameraUseCase to simplify some functions
- Use double tap for switching CaptureMode instead of lens (temporary change)
=> Add support for single stream capture

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt, feature/preview/src/main/res/values/strings.xml, feature/quicksettings/src/main/java/com/google/jetpackcamera/feature/quicksettings/QuickSettingsScreen.kt, feature/quicksettings/src/main/java/com/google/jetpackcamera/feature/quicksettings/ui/QuickSettingsComponents.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/ui/SettingsComponents.kt
Refactored UI for better appearance, readability, and maintainability; _**There is no change in functionality and minimal change in appearance.**_ 
Here's a brief summary of the changes in this PR:
* Compartmentalized the logic that already exists within the `/preview/PreviewScreen.kt`, and moved most of it into `/preview/ui/PreviewScreenComponents.kt`. Big adjustments on use of containers and modifiers.
* Adjusted some modifiers for `QuickSettingsScreen.kt`; 
* I added a "flip camera" button to the preview screen for easier access
* I also added minor styling changes to the Settings screen; added colors and adjusted some spacing.
=> Refactor Preview UI

build.gradle.kts, hooks/pre-commit
The pre-commit git hook will be installed when running any gradle command.
Before `git commit` is run, Spotless will apply fixes for any automatic fixes, and fail if manual fixes are needed.
=> Create a pre-commit git hook to run spotlessApply, along with a gradle task to install the hook

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt
A better fix than https://github.com/google/jetpack-camera-app/pull/58
When camera is flipped, it is not assigned to a runningCameraJob, this caused the CorotineCameraProvider to not be able to unbind camera on job cancelled
=> Backgrounding crash fix

.github/workflows/PushWorkflow.yaml, .idea/gradle.xml
Increase the timeout for build and test jobs. Due to androidx.dev maven repository being slow, our CI builds are timing out.
=> Increase timeout for build and test jobs

app/src/androidTest/java/com/google/jetpackcamera/BackgroundDeviceTest.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/quicksettings/src/main/java/com/google/jetpackcamera/feature/quicksettings/QuickSettingsScreen.kt, feature/quicksettings/src/main/java/com/google/jetpackcamera/feature/quicksettings/ui/QuickSettingsComponents.kt
setCaptureMode() and setAspectRatio() also invokes rebindUseCase(), before which the old runningCameraJob needs to be stopped and updated
=> Stop RuningCameraJob on all rebindUseCase() instances

app/src/main/java/com/google/jetpackcamera/JetpackCameraApplication.kt, app/src/main/java/com/google/jetpackcamera/ui/JcaApp.kt, app/src/main/java/com/google/jetpackcamera/ui/Routes.kt, app/src/main/java/com/google/jetpackcamera/ui/theme/Color.kt, app/src/main/java/com/google/jetpackcamera/ui/theme/Theme.kt, app/src/main/java/com/google/jetpackcamera/ui/theme/Type.kt, camera-viewfinder-compose/src/main/java/com/google/jetpackcamera/viewfinder/CameraPreview.kt, camera-viewfinder-compose/src/main/java/com/google/jetpackcamera/viewfinder/surface/CombinedSurface.kt, camera-viewfinder-compose/src/main/java/com/google/jetpackcamera/viewfinder/surface/Surface.kt, camera-viewfinder-compose/src/main/java/com/google/jetpackcamera/viewfinder/surface/SurfaceTransformationUtil.kt, camera-viewfinder-compose/src/main/java/com/google/jetpackcamera/viewfinder/surface/Texture.kt, data/settings/src/androidTest/java/com/google/jetpackcamera/settings/DataStoreModuleTest.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/DataStoreModule.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/SettingsModule.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/model/AspectRatio.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/model/CaptureMode.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/test/FakeDataStoreModule.kt, data/settings/src/test/java/com/google/jetpackcamera/settings/ExampleUnitTest.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewUiState.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsUiState.kt
Ran `spotlessApply` and fixed all issues that caused errors. Some
automatic fixes were applied after fixing manual issues.
This required temporarily turning off
`ratchetFrom("origin/main")`
=> Apply all spotless fixes that required manual intervention

domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt
The capture mode labels were reversed. This change fixes that.
=> Fix capture mode labels in filenames

.github/workflows/PullRequestWorkflow.yaml
Some of our CI tests are not triggering when there's a new pull request from outside of the repository.
This should be fixed by changing the event it's triggered on to `pull_request` instead of `push`
=> Update CI to run on pull requests instead of push

data/settings/src/main/java/com/google/jetpackcamera/settings/LocalSettingsRepository.kt
updateAvailableCameraLens function always set the settings of front facing camera to true if the front facing camera is available, by removing the call to setDefaultFrontCamera the front camera is not set to true as a default value and fix the issue.
=> Fix reset of front facing camera settings after leaving screen settings

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/ToastMessage.kt
ToastMessage takes a stringResource Int instead of a string.
remove toast test descriptions to avoid potential conflict with accessibility reader
=> ToastMessage adjustments

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt, feature/quicksettings/src/main/java/com/google/jetpackcamera/feature/quicksettings/QuickSettingsScreen.kt, feature/quicksettings/src/main/java/com/google/jetpackcamera/feature/quicksettings/ui/QuickSettingsComponents.kt
**Low priority**
when working on adding an icon in the preview screen for [pr #83](https://github.com/google/jetpack-camera-app/pull/83), I noticed it was a bit difficult to "neatly" insert new elements into the top bar; I made a small refactor to `previewScreen` to make it easier to do so. This will facilitate the addition of future potential elements to the preview screen such as a vertical side bar. 
Most important about the change:
* Preview screen buttons/icons overlay layer has more of a grid-relative layout -- no more free-floating elements in boxes 🎈 
* Top row of icons is a 3-segmented row similar to how the bottom row was implemented
* `QuickSettingsScreen` has been decoupled from its toggle button
Screenshots below use colors to show how the overlay is divided
Magenta = parent …
=> Preview screen layout refactor

app/build.gradle.kts, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/quicksettings/src/main/java/com/google/jetpackcamera/feature/quicksettings/QuickSettingsScreen.kt
This PR resolves the problem by moving enabling `testTagsAsResourceId` in a parent box holding all preview composables.
**_So what happened?_**
[Refactoring the Preview Screen](#96) moved `QuickSettingsScreenOverlay` outside of the parent component that sets semantics `testTagsAsResourceId = true`.
`testTagsAsResourceId` should only be invoked _once_ high in the composable hierarchy to ensure all tagged, nested components are visible to UiAutomator. [read more about it on Android Developers](testTagsAsResourceId)
=> Fix issue where UiAutomator cannot find components

data/settings/build.gradle.kts
there was a typo in `data/settings/build.gradle.kts` when migrating to version catalogs in #95
=> fix dependency issue causing test failures in :data:settings

spotless/copyright.kt, spotless/copyright.kts, spotless/copyright.xml
The year will now be updated to the current year rather than
being changed back to 2023 by spotlessApply
=> Update copyright header year in spotless

data/settings/src/main/java/com/google/jetpackcamera/settings/model/CameraAppSettings.kt, domain/camera/build.gradle.kts, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraUseCase.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/test/FakeCameraUseCase.kt, domain/camera/src/test/java/com/google/jetpackcamera/domain/camera/test/FakeCameraUseCaseTest.kt, feature/preview/build.gradle.kts, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/test/java/com/google/jetpackcamera/feature/preview/PreviewViewModelTest.kt, feature/preview/src/test/java/com/google/jetpackcamera/feature/preview/ScreenFlashTest.kt
- Update CameraUseCase to reactive model
- CameraUseCase is only place where default settings will be applied
- PreviewViewModel should not edit CameraAppState
- Setting aspect ratio and flipping camera no longer restarts camera job
=> Single source of truth for camera settings

app/src/androidTest/java/com/google/jetpackcamera/ComposeTestRuleExt.kt, app/src/androidTest/java/com/google/jetpackcamera/NavigationTest.kt, app/src/main/java/com/google/jetpackcamera/ui/JcaApp.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/CameraControlsOverlay.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/TestTags.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/ui/SettingsComponents.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/ui/TestTags.kt
When the back arrow is pressed on `SettingsScreen`, `navController.navigate(PREVIEW_ROUTE)` was being called, which added `SettingsScreen` to the back stack. Instead, `navController.popBackStack()` can be used to return to the previous screen, mimicking the behavior of using the device's back button (or back gesture).
=> Pop from back stack when Settings back arrow is pressed

domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt
fixes #118 
`adb shell cmd media.camera watch start -m android.control.videoStabilizationMode && adb shell cmd media.camera watch live`
note the changes when applied in default settings currently requires the app to be relaunched to take effect
=> fix stabilization issue

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/CameraControlsOverlay.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/ToastMessage.kt, feature/preview/src/main/res/values/strings.xml
This change has two (mostly) cosmetic changes.
1.)  **zoom scale text** is now  centered on the screen instead of being shifted to the left
2.) When using`TestableToast`, the display of a system toast is now optional. 
The composable responsible for triggering the Toast display will still be visible to UiAutomator (UI automator only checks for the presence of the composable, not the visibility).
=> small visual updates

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/CameraControlsOverlay.kt
This somehow didn't make it into #125, even though a test
was written that depended on it
=> Add FLIP_CAMERA_BUTTON test tag

.github/workflows/PullRequestWorkflow.yaml
See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Update github actions to use node20

core/common/build.gradle.kts, core/common/src/main/java/com/google/jetpackcamera/core/common/RefCounted.kt, core/common/src/test/java/com/google/jetpackcamera/core/common/RefCountedTest.kt, gradle/libs.versions.toml
This is used for shared state between threads.
It will allow us to track and release Surface usage
between a GL thread and the main thread.
Example of how it is being used [here](https://github.com/google/jetpack-camera-app/pull/132/files#diff-2c5c256dae5a6352542cb2bad6539b3bb4a36935bc7d845c014315339c4bd9ab)
=> Add RefCounted class

data/settings/src/main/java/com/google/jetpackcamera/settings/JcaSettingsSerializer.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/LocalSettingsRepository.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/test/FakeJcaSettingsSerializer.kt
Replace some usage of boolean lens facing tracking with enum version
that was missed in #133
=> Remove usages of deprecated proto fields

app/build.gradle.kts, app/src/main/java/com/google/jetpackcamera/ui/JcaApp.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/ui/SettingsComponents.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/ui/theme/Theme.kt, feature/settings/src/main/res/values/strings.xml
Display version information from gradle's generated BuildConfig
in the app setting screen
Also adds ability to preview settings screen using Compose previews
=> Show version information in SettingsScreen

feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt
- The settings screen column didn't have a background, so during
the transition animation, any elements without a background
use the old background until the transition is complete. This
adds a background to the settings screen column.
**Before**:
**After**:
=> Fix settings screen transition animation

app/src/androidTest/java/com/google/jetpackcamera/AppTestUtil.kt, app/src/androidTest/java/com/google/jetpackcamera/BackgroundDeviceTest.kt, app/src/androidTest/java/com/google/jetpackcamera/FlashDeviceTest.kt, app/src/androidTest/java/com/google/jetpackcamera/ImageCaptureDeviceTest.kt, app/src/androidTest/java/com/google/jetpackcamera/NavigationTest.kt, app/src/androidTest/java/com/google/jetpackcamera/SwitchCameraTest.kt, app/src/main/AndroidManifest.xml
We need the WRITE_EXTERNAL_STORAGE permission on API 28, so
add it to the GrantPermissionRule.
Renames FlashDeviceTest#set_screen_flash_and_capture_successfully to
set_flash_and_capture_successfully, since this is using the rear camera.
The test will be skipped if the device doesn't have a rear camera.
Limits the WRITE_EXTERNAL_STORAGE permission to maxSdk 28 since
it is not needed with ScopeStorage.
Removes unused READ_EXTERNAL_STORAGE permission.
=> Fix broken FlashDeviceTest

settings.gradle.kts
This bumps the snapshot version to the build that includes
aosp/3029366.
=> Bump CameraX version for temporal noise fix

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt
https://github.com/google/jetpack-camera-app/assets/125502967/10bad22f-f28f-43ad-8904-7d08312b4c28
Everytime a new snackbar shows, the old one is dismissed. Making it always a queue of 1 and reflecting the latest capture
=> SnackBar queueing fix

feature/preview/build.gradle.kts, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewUiState.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/SnackbarData.kt
Uses LaunchedEffect rather than the coroutineScope passed in.
Adds a cookie field SnackBarData so it can be differentiated from
other SnackBarData.
Updates a counter for each ImageCapture and VideoCapture which
is used to generate the cookie for SnackBarData. This is also
used as the cookie for the image capture trace.
These changes will also ensure that TestableSnackbar's tagged
Box is visible for as long as the Snackbar is.
Renames usage of SnackBar -> Snackbar to match framework component
=> Make TestableSnackbar more robust

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/CameraXViewfinder.kt, settings.gradle.kts
- Now uses EMBEDDED and EXTERNAL instead of PERFORMANCE and COMPATIBLE
- Also includes fixes to display EMBEDDED correctly & proper surface
release logic.
=> Update to CameraX viewfinder-compose snapshot with API changes

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/theme/Theme.kt
This adds a ui component that can be used to choose between image capture and video capture when HDR is enabled:
The button can be disabled for the case that only HDR video is supported
The animation for transition between different states is also implemented for completeness.
=> Add ToggleButton ui component

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt
Temporary fix for #207 until we fix the problem in camerax-viewfinder-compose
=> Use EMBEDDED ImplementationMode when SDK level is <= 24

domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt
The FOV issue is fixed by setting the resolutionSelector with the right aspectRatios. I just confused myself and set the aspect ratio incorrectly.
Preview:
https://github.com/google/jetpack-camera-app/assets/125502967/bc5f52d2-854c-4690-b2ff-990ccc90d2bb
Image:
Video:
https://github.com/google/jetpack-camera-app/assets/125502967/8b17c37f-c9e7-4c74-a3d6-55214d79316d
https://github.com/google/jetpack-camera-app/assets/125502967/18fef4a3-4c47-4325-9b26-7bc7cc453dbe
=> ResolutionSelector aspectRatio fix

domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt
as titled. We want 4:3 to be the default because it is the uncropped one. Simple change
=> use 4:3 as the default aspect ratio for camera use cases in case of 1:1

app/src/main/java/com/google/jetpackcamera/ui/JcaApp.kt, feature/permissions/src/main/java/com/google/jetpackcamera/permissions/PermissionsScreen.kt
As titled.
I didn't add or modify any test for this because I think it makes sense to work on top of Kim's permission tests. I did locally tested removing the audio permission in ImageCaptureDeviceTest, and observed that the external intent capture tests would pass and the standard capture would fail.
=> Only request audio permission in Standard mode

.github/workflows/PullRequestWorkflow.yaml
Use stable debug builds in the CI instrumentation tests.
Fix for #235
=> Update PullRequestWorkflow to use stable debug builds

data/settings/src/main/java/com/google/jetpackcamera/settings/model/AspectRatio.kt, domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewUiState.kt
1:1 is not a natively supported aspect ratio for CameraX. We had
defaulted to using 4:3 and cropping since most sensors are 4:3.
However, some emulators may use a 16:9 aspect ratio for their
sensor, so we should instead use the aspect ratio which is closest
to the sensor aspect ratio so we maximize support for emulators
while also maximizing the FOV.
=> Use nearest sensor aspect ratio for 1:1

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt
Adds a rounded corner shaped clip to the Viewfinder using compose
=> Add rounded corners to viewfinder

core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraUseCase.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCase.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/test/FakeCameraUseCase.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/model/CameraAppSettings.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/model/DeviceRotation.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/DebouncedOrientationFlow.kt
Videos and images will be captured based on the orientation
of the device. This is independent of the screen's orientation,
which will currently still be locked to portrait.
=> Make captures use gyro to determine orientation

.gitignore, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraUseCase.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCase.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/test/FakeCameraUseCase.kt, core/camera/src/test/java/com/google/jetpackcamera/core/camera/test/FakeCameraUseCaseTest.kt, feature/preview/build.gradle.kts, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/test/java/com/google/jetpackcamera/feature/preview/PreviewViewModelTest.kt, feature/preview/src/test/java/com/google/jetpackcamera/feature/preview/ScreenFlashTest.kt, gradle/libs.versions.toml
Changes made on default settings screen are now immediately active on Camera.
Notable Changes:
* Moved default settings flow out of  `CameraXCameraUseCase` and into `PreviewViewModel`
* Map only the NEW changes from default settings and apply them to `CameraXCameraUseCase`
* New Settings added to settings screen must be accounted for in `applySettingsDiff()` function, or will throw a `TODO()` error when attempting to change the setting
* Frame rate and stabilization settings  apply following constraints
_May experience some unintended behavior, as settings still need to be locked to SystemConstraints to prevent invalid settings configurations._
closes #174
=> Immediately sync default settings changes to camera

core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraEvent.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCase.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CoroutineCameraProvider.kt
* Ensure coroutines launched in runWith use correct parent scope
Ensures coroutines in runWith are launched within the runWith
coroutineScope so cancellation will be applied properly.
* Process tap-to-focus events within camera coroutine
Pushes points directly to the camera coroutine which will
wait for SurfaceRequests to create the
SurfaceOrientedMeteringPointFactory before processing them.
Any tap-to-focus events that happen without a SurfaceRequest
will be ignored.
=> Fix child coroutines in runWith scope and update focus events

core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCase.kt
1. Only use the DeviceRotation to set the targetRotation for
ImageCapture and VideoCapture. Preview should reflect the
display rotation. DeviceRotation only comes from the gyro
and may not match the display rotation, which comes from
the `screenRotation` attribute of the AndroidManifest.
2. Ensure we initialize the device rotation immediately after
calling `runWith` (or `bindToLifecycle`). The ViewPort will
reset the targetRotations of ImageCapture and VideoCapture
to match the Preview targetRotation, which is not what we
want when the device is physically rotated in an orientation
other than the display rotation.
=> Properly handle device / display rotation for fixed portrait app

core/camera/src/test/java/com/google/jetpackcamera/core/camera/test/FakeCameraUseCaseTest.kt
This test was missed during the concurrent camera refactor.
Fixed with two changes fixing build failures.
=> Fix FakeCameraUseCaseTest compilation errors

app/src/androidTest/java/com/google/jetpackcamera/ImageCaptureDeviceTest.kt, app/src/androidTest/java/com/google/jetpackcamera/VideoRecordingDeviceTest.kt, app/src/androidTest/java/com/google/jetpackcamera/utils/UiTestUtil.kt
See issue at
https://github.com/android/android-test/issues/676
=> Workaround androidx.test 45 second timeout in ActivityScenario

core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCase.kt
This fixes the open failed: EACCES issue
=> Save Camera Properties to android/data/com.google.jetpackcamera instead of Documents

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/CameraControlsOverlay.kt
As titled. To make it more convenient for ITS test_zoom. This is reasonable since we want to display as much information in debug mode anyway
=> debug mode always shows preview zoom ratio

app/src/androidTest/java/com/google/jetpackcamera/ImageCaptureDeviceTest.kt, app/src/main/java/com/google/jetpackcamera/MainActivity.kt
When JCA is launched with INTENT_ACTION_STILL_IMAGE_CAMERA into ExternalMultipleImageCaptureMode, if the uris are not supplied, populate the resultIntent with a list of strings. These strings can be either uris from successful captures or errorMessages from failed captures. The key is MediaStore.EXTRA_OUTPUT ("output"), same as the key for supplying uris.
=> Multiple Image Capture Result Data

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/CameraControlsOverlay.kt
✅ This change adds a modifier to prevent the top controls from occupying the status bar.
🗒️ Context: For some devices, such as the Pixel 9 Pro XL, `Modifier.fillMaxHeight` will cause UI elements to fill to the the top edge of the device's screen. While it is ok for  parts of the app (such as viewfinder) to extend to the top edge of the screen, elements such as buttons should not. 
🧠 For more reference, refer to this Android Developers guide: **[Display content edge-to-edge in your app and handle window insets in Compose](https://developer.android.com/develop/ui/compose/layouts/insets)**
=> Fix bug causing top app controls to invade the top status bar

core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraSession.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraSessionContext.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCase.kt
Added a private var to keep track of zoomScale of the cameras (mapped to lensFacing). This is needed because camera.cameraInfo.zoomState.zoomScale resets to 1 at some point after runSingleCameraSession. See the buggy video below:
https://github.com/user-attachments/assets/23a5128f-c86f-4b4a-b511-d65595053be8
So instead of using cameraInfo.zoomState to keep track of the current zoomScale, have our own var to do this bypass the bug. Below is the fixed behavior (I also verified lens flipping persistence but didn't include it in the video):
https://github.com/user-attachments/assets/137db24c-bd8d-4c54-9447-451a6b6ee6a0
=> ZoomScale persistence 

app/src/main/java/com/google/jetpackcamera/ui/JcaApp.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/quicksettings/QuickSettingsScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/quicksettings/ui/QuickSettingsComponents.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/CameraControlsOverlay.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/ui/SettingsComponents.kt
Some cosmetic UI changes. summary:
_Minor changes to existing:_
* added padding to bottom capture controls to avoid snackbar overlap
* hide the square, grayish touch indicator present on some clickable components
_new animations:_
* slide transition when opening settings screen
* bouncy buttons 
* flip camera icon spins whenever lensfacing changes
* smoother animations for quick settings drop down
* animation for for focusing (expanding) a quick setting
_Mild non-cosmetic refactors:_
* renamed ExpandedQuickSetting to FocusedQuickSetting
**_Android Developers page on_** [**_Animation Modifiers and Composables_**](https://developer.android.com/develop/ui/compose/animation/composables-modifiers)
https://github.com/user-attachments/assets/f4c8818e-951a-4b7d-8d94-215d18227645
=> Preview Cosmetic Animations

core/camera/src/androidTest/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCaseTest.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraSession.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraSessionSettings.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraUseCase.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCase.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/ConcurrentCameraSession.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/test/FakeCameraUseCase.kt, core/camera/src/test/java/com/google/jetpackcamera/core/camera/test/FakeCameraUseCaseTest.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/model/CameraAppSettings.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/model/CaptureMode.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt, feature/preview/src/test/java/com/google/jetpackcamera/feature/preview/ScreenFlashTest.kt
effectively convert `UseCaseMode` to `CaptureMode`, and move into `CameraAppSettings`.
Update references to UseCaseMode account for captureMode now residing in `CameraAppSettings`.
`CameraAppSettings.applyPreviewMode()` in viewModel to initialize the CameraAppSettings captureMode to `VIDEO_ONLY` or `IMAGE_ONLY` if the PreviewMode doesn't support `STANDARD`
=> update  UseCaseMode to CaptureMode

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/quicksettings/QuickSettingsScreen.kt
concurrent camera setting is still enabled while HDR quick setting is active. 
🐛  the app will crash when attempting to enable concurrent camera while HDR image capture is enabled.
✅ this change simply disables the concurrent camera quick setting while HDR image or HDR video is enabled
=> fixes crashing bug between image HDR and concurrent quicksettings

data/settings/src/main/java/com/google/jetpackcamera/settings/model/CameraAppSettings.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/model/Constraints.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsUiState.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsViewModel.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/ui/SettingsComponents.kt, feature/settings/src/main/res/values/strings.xml
Default flash setting will now be disabled with an appropriate message when:
* device only supports `OFF`
* default lens only supports `OFF`
Default flash options will be disabled if the current lens doesnt support the particular mode.
important stuff to check is in `SettingsViewModel`
=> add constraints to flash setting

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/quicksettings/QuickSettingsScreen.kt
user will no longer be able to switch to single-stream capture while HDR image capture is on
=> disable single stream quick setting while Ultra HDR Image capture is active

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt
pausing a pressed recording would cause the ui to treat it as a locked recording
=> fix pause while recording bug

app/src/androidTest/java/com/google/jetpackcamera/utils/ComposeTestRuleExt.kt
Code changes in #324 increased the recording time to 3 seconds.
Because the video_capture_illegal_uri test fails the video recording
immediately when it is started, the snackbar that showed that the
video capture failed was shown and dismissed before the 3 seconds
elapsed, so the snackbar was not available when checking at the end
of the test.
This change causes the idling for video recording to exit early if
there is a video recording failure. This allows the snack bar
message to be tested on failure.
=> Fix VideoRecordingDeviceTest illegal URI test failure

app/src/androidTest/java/com/google/jetpackcamera/ConcurrentCameraTest.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/quicksettings/QuickSettingsScreen.kt
The capture mode toggle switch was removed in #324 when concurrent
camera mode is enabled.  We can now check the quick setting button
for the capture mode.
=> Fix ConcurrentCameraTest failure

app/build.gradle.kts, app/src/androidTest/java/com/google/jetpackcamera/ImageCaptureDeviceTest.kt, app/src/androidTest/java/com/google/jetpackcamera/PermissionsTest.kt, app/src/androidTest/java/com/google/jetpackcamera/utils/ComposeTestRuleExt.kt, app/src/androidTest/java/com/google/jetpackcamera/utils/UiTestUtil.kt, app/src/main/java/com/google/jetpackcamera/ui/JcaApp.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraSession.kt, feature/permissions/src/main/java/com/google/jetpackcamera/permissions/PermissionsEnums.kt, feature/permissions/src/main/java/com/google/jetpackcamera/permissions/PermissionsScreen.kt, feature/permissions/src/main/java/com/google/jetpackcamera/permissions/PermissionsViewModel.kt, feature/permissions/src/main/java/com/google/jetpackcamera/permissions/ui/PermissionsScreenComponents.kt, feature/permissions/src/main/java/com/google/jetpackcamera/permissions/ui/TestTags.kt, feature/permissions/src/main/res/values/strings.xml, feature/preview/build.gradle.kts, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/ImageWell.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/TestTags.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt, gradle/libs.versions.toml
Fixes #348
adds read/write permission screens.
Sometimes, granting the write permission will automatically grant the read permission as well. if that is the case, the read permission screen will be skipped. If not, the read permission screen will still be displayed
=> Add storage permission screens

core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCase.kt
This `tryApplyVideoQualityConstraints` function was added in #324 and it was applied twice.
See line 274 and 276
https://github.com/google/jetpack-camera-app/blob/668eac5183f545eb8d2a94c60e76787d284e6c23/core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCase.kt#L274
https://github.com/google/jetpack-camera-app/blob/668eac5183f545eb8d2a94c60e76787d284e6c23/core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCase.kt#L276
=> Remove a duplicated extension function.

app/build.gradle.kts, app/src/androidTest/java/com/google/jetpackcamera/ConcurrentCameraTest.kt, app/src/androidTest/java/com/google/jetpackcamera/SwitchCameraTest.kt, app/src/androidTest/java/com/google/jetpackcamera/utils/AppTestUtil.kt, app/src/androidTest/java/com/google/jetpackcamera/utils/ComposeTestRuleExt.kt, app/src/androidTest/java/com/google/jetpackcamera/utils/UiTestUtil.kt
Add @IgnoreReturnValue to visitQuickSettings() and set unused return values to "val unused".
Removed the context receiver usage in ConcurrentCameraTest.
=> Ignore returned values and remove context receiver in device tests

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt, ui/components/capture/src/main/java/com/google/jetpackcamera/ui/components/capture/CaptureScreenComponents.kt
In #363, the rememberUpdatedState() was removed. This cause the flipLensUiState used here being not updated. Use rememberUpdatedState() to track the updated uiState.
#381 shows the debugging process
=> Fix double tap lens flipping bug

README.md, scripts/git-hooks/pre-push
Adds a `pre-push` Git hook to automatically verify code formatting
before code is pushed.
The hook runs `./gradlew spotlessCheck` to ensure code adheres to
project style guidelines. This prevents CI failures caused by
formatting errors and helps maintain a consistent codebase.
To enable this, developers must run this command once:
`git config core.hooksPath scripts/git-hooks`
The check can be bypassed for a single push using the `--no-verify`
flag. Setup instructions have been added to README.md.
=> Add Spotless pre-push hook

benchmark/src/main/java/com/google/jetpackcamera/benchmark/ImageCaptureLatencyBenchmark.kt, core/camera/src/androidTest/java/com/google/jetpackcamera/core/camera/CameraXCameraSystemTest.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraModule.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraSession.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraSessionContext.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraState.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraSystem.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraXCameraSystem.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/VideoCaptureControlEvent.kt, core/camera/src/main/java/com/google/jetpackcamera/core/camera/test/FakeCameraSystem.kt, core/camera/src/test/java/com/google/jetpackcamera/core/camera/test/FakeCameraSystemTest.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/ConstraintsRepository.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/model/CameraAppSettings.kt, data/settings/src/main/java/com/google/jetpackcamera/settings/model/Constraints.kt, feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt, feature/preview/src/test/java/com/google/jetpackcamera/feature/preview/PreviewViewModelTest.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsUiState.kt, feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsViewModel.kt, ui/components/capture/src/main/java/com/google/jetpackcamera/ui/components/capture/ScreenFlash.kt, ui/components/capture/src/test/java/com/google/jetpackcamera/ui/components/capture/capture/ScreenFlashTest.kt, ui/uistateadapter/capture/src/main/java/com/google/jetpackcamera/ui/uistateadapter/capture/CaptureModeUiStateAdapter.kt, ui/uistateadapter/capture/src/main/java/com/google/jetpackcamera/ui/uistateadapter/capture/ConcurrentCameraUiStateAdapter.kt, ui/uistateadapter/capture/src/main/java/com/google/jetpackcamera/ui/uistateadapter/capture/DebugUiStateAdapter.kt, ui/uistateadapter/capture/src/main/java/com/google/jetpackcamera/ui/uistateadapter/capture/FlashModeUiStateAdapter.kt, ui/uistateadapter/capture/src/main/java/com/google/jetpackcamera/ui/uistateadapter/capture/FlipLensUiStateAdapter.kt, ui/uistateadapter/capture/src/main/java/com/google/jetpackcamera/ui/uistateadapter/capture/HdrUiStateAdapter.kt, ui/uistateadapter/capture/src/main/java/com/google/jetpackcamera/ui/uistateadapter/capture/ZoomControlUiStateAdapter.kt, ui/uistateadapter/capture/src/main/java/com/google/jetpackcamera/ui/uistateadapter/capture/ZoomUiStateAdapter.kt
This commit renames CameraUseCase to CameraSystem to avoid confusion with the "UseCase" pattern from Clean Architecture. The previous name was misleading, as the class did not follow that specific architectural pattern.
The new name, CameraSystem, more accurately reflects the class's role as the primary, high-level interface for interacting with the device's camera hardware and subsystems.
=> Rename CameraUseCase to CameraSystem
