feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt

fixed bug where double-tap to flip camera wasn't working

enable double-tap to flip camera

---

data/settings/src/main/java/com/google/jetpackcamera/settings/JcaSettingsSerializer.kt
data/settings/src/main/java/com/google/jetpackcamera/settings/LocalSettingsRepository.kt
data/settings/src/main/java/com/google/jetpackcamera/settings/SettingsRepository.kt
data/settings/src/main/java/com/google/jetpackcamera/settings/model/AspectRatio.kt
data/settings/src/main/java/com/google/jetpackcamera/settings/test/FakeSettingsRepository.kt
data/settings/src/main/proto/com/google/jetpackcamera/settings/aspect_ratio.proto
data/settings/src/main/proto/com/google/jetpackcamera/settings/jca_settings.proto
feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt
feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsViewModel.kt
feature/settings/src/main/java/com/google/jetpackcamera/settings/ui/SettingsComponents.kt
feature/settings/src/main/res/values/strings.xml

Add set default aspect ratio to settings screen

Aspect Ratio Setting

---

.idea/misc.xml
.idea/vcs.xml
data/settings/src/main/java/com/google/jetpackcamera/settings/JcaSettingsSerializer.kt
data/settings/src/main/java/com/google/jetpackcamera/settings/LocalSettingsRepository.kt
data/settings/src/main/java/com/google/jetpackcamera/settings/SettingsRepository.kt
data/settings/src/main/java/com/google/jetpackcamera/settings/model/CameraAppSettings.kt
data/settings/src/main/java/com/google/jetpackcamera/settings/model/CaptureMode.kt
data/settings/src/main/java/com/google/jetpackcamera/settings/model/CaptureModeStatus.kt
data/settings/src/main/java/com/google/jetpackcamera/settings/test/FakeSettingsRepository.kt
data/settings/src/main/proto/com/google/jetpackcamera/settings/capture_mode.proto
data/settings/src/main/proto/com/google/jetpackcamera/settings/jca_settings.proto
domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraUseCase.kt
domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt
domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/test/FakeCameraUseCase.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewUiState.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt
feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt
feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsViewModel.kt
feature/settings/src/main/java/com/google/jetpackcamera/settings/ui/SettingsComponents.kt
feature/settings/src/main/res/values/strings.xml

Self explanatory. Most interesting changes to review is integration in `CameraXCameraUseCase`
* create enum representing capture type for camera
* create setting to store default value for capture type
* update CameraXCameraUseCase to use enum value

Capture Mode Setting and Integration

---

.editorconfig
.gitignore
gradle/init.gradle.kts
spotless/copyright.kt
spotless/copyright.kts
spotless/copyright.xml

Run using 
./gradlew spotlessCheck --init-script gradle/init.gradle.kts --stacktrace
Apply automatic changes using
./gradlew spotlessApply --init-script gradle/init.gradle.kts --stacktrace

Add Spotless with ktlint to the project

---

app/build.gradle.kts
build.gradle.kts
camera-viewfinder-compose/build.gradle.kts
core/common/build.gradle.kts
data/settings/build.gradle.kts
domain/camera/build.gradle.kts
feature/preview/build.gradle.kts
feature/quicksettings/build.gradle.kts
feature/settings/build.gradle.kts
settings.gradle.kts

- Adding the AOSP copyright notice to gradle files

Add Copyright notice to gradle files

---

domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraUseCase.kt

This is the 1st PR in a chain to refactor CameraUseCase to enforce UDF (Unidirectional Data Flow).
This data class will act as the holder for camera related configurations.
We can observe the StateFlow<Config> from ViewModel in order to generate the necessary values for views, while respecting UDF.

Create a Configuration data class to use with CameraUseCase implementations

---

.github/workflows/MergeToMainWorkflow.yaml

Create a workflow that will do a build whenever a commit it pushed to main branch

Create a build workflow for merging into main branch

---

feature/preview/build.gradle.kts
feature/quicksettings/build.gradle.kts
feature/settings/build.gradle.kts
gradle/libs.versions.toml

Remove dependency on full Guava library

---

feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsScreen.kt

hiding this setting until #118 is resolved

hide stabilization setting until issue is resolved

---

app/build.gradle.kts
app/src/androidTest/java/com/google/jetpackcamera/FlashDeviceTest.kt
app/src/androidTest/java/com/google/jetpackcamera/UiTestUtil.kt
app/src/main/java/com/google/jetpackcamera/MainActivity.kt
app/src/main/java/com/google/jetpackcamera/ui/JcaApp.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt

Just verify the UI is correct instead of keeping data in MainActivity for testing

Remove PreviewViewModel in app module for testing

---

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt

Change flip camera icon in preview screen

---

domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraEvent.kt
domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraUseCase.kt
domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/CameraXCameraUseCase.kt
domain/camera/src/main/java/com/google/jetpackcamera/domain/camera/test/FakeCameraUseCase.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewScreen.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/CameraXViewfinder.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt

It looks to me as if there's some jank when starting focus and metering. Let me know what you think
https://github.com/google/jetpack-camera-app/assets/417355/bbc0817e-741e-4859-a1c7-706d5147c0d5

Add tap to focus feature using the coordinate transformer in viewfinder

---

core/camera/build.gradle.kts
core/camera/src/androidTest/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCaseTest.kt
core/camera/src/androidTest/java/com/google/jetpackcamera/core/camera/utils/AppTestUtil.kt
core/camera/src/main/AndroidManifest.xml
core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraUseCase.kt
core/camera/src/main/java/com/google/jetpackcamera/core/camera/CameraXCameraUseCase.kt
core/camera/src/main/java/com/google/jetpackcamera/core/camera/CoroutineCameraProvider.kt
core/camera/src/main/java/com/google/jetpackcamera/core/camera/VideoCaptureControlEvent.kt
data/settings/src/main/java/com/google/jetpackcamera/settings/model/Constraints.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt
gradle/libs.versions.toml

* The torch will be enabled when receiving VideoRecordEvent.Start and disabled when receiving VideoRecordEvent.Finalize.
* Add CameraXCamerauseCaseTest.

Enable torch when video recording and flash mode is ON

---

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/CameraControlsOverlay.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/TestTags.kt

Add a test tag for zoom ratio
Add the testTag directly to the Text component so ITS can pull its text content more easily

Zoom ratio tag

---

feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewUiState.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/CameraControlsOverlay.kt
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/ui/PreviewScreenComponents.kt

small refactor to give elapsed time a uistate.
should be visible long enough for future tests that want to track duration

Elapsed time UI state

---

README.md

Adds documentation with a TOC for all features

Add documentation for app features to README

---

feature/settings/src/main/res/values/strings.xml

Both AOSP and google3 complains about this during merging

Remove the extra backlash in String.xml

---

feature/postcapture/build.gradle.kts
feature/preview/build.gradle.kts
feature/preview/src/main/java/com/google/jetpackcamera/feature/preview/PreviewViewModel.kt
feature/settings/src/main/java/com/google/jetpackcamera/settings/SettingsViewModel.kt
gradle/libs.versions.toml

This replaces the use of kotlin reflection, which is known to
have unnecessary performance overhead

Remove usage of kotlin reflection

---

.github/workflows/PullRequestWorkflow.yaml

Add cache encryption key to Instrumentation Tests job

---

app/src/androidTest/java/com/google/jetpackcamera/CaptureModeSettingsTest.kt
app/src/androidTest/java/com/google/jetpackcamera/ImageCaptureDeviceTest.kt
app/src/androidTest/java/com/google/jetpackcamera/PermissionsTest.kt
app/src/androidTest/java/com/google/jetpackcamera/VideoRecordingDeviceTest.kt
app/src/androidTest/java/com/google/jetpackcamera/utils/AppTestUtil.kt

Move the MOVIES & PICTURES dir paths from within tests to AppTestUtil so test classes don't depend on one another

Remove test inter-dependency

---

app/src/androidTest/java/com/google/jetpackcamera/ConcurrentCameraTest.kt

So that there is no unused return value

Replace any with foreach in ConcurrentCameraTest

---

.gemini/styleguide.md

introduces a styleguide to help direct the behavior of gemini's integration in this repository

introduce new styleguide for gemini
